name: Get Total Issues Gist

on:
  schedule:
    - cron: "10 * * * *" # runs every hour at :10
  workflow_dispatch:

jobs:
  update-gists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Count all open issues
        run: python scripts/count_stats.py
        env:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}

      - name: update gist
        run: |
          gist_id=2cb0ef8788a0f3a9f061df669baeb90c
          file_name=total-issues.json
          gh gist edit $gist_id $file_name
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
